name: ClawChat
options:
  bundleIdPrefix: com.yourcompany  # Replace with your bundle ID prefix
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
targets:
  ClawChat:
    type: application
    platform: iOS
    sources:
      - path: Therin
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.clawchat  # Replace with your bundle ID
        PRODUCT_NAME: ClawChat
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: XXXXXXXXXX  # Replace with your Apple Developer Team ID
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_GENERATION_MODE: GeneratedByXcode
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    info:
      path: ClawChat-Info.plist
      properties:
        CFBundleDisplayName: ClawChat
        CFBundleName: ClawChat
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: ClawChat uses the microphone for voice input to send messages
        NSSpeechRecognitionUsageDescription: ClawChat uses speech recognition to transcribe your voice messages
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
