name: ClawChat
options:
  bundleIdPrefix: io.kleidia
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
targets:
  ClawChat:
    type: application
    platform: iOS
    sources:
      - path: Therin
    # Uncomment when App Group is configured in Apple Developer Portal:
    # dependencies:
    #   - target: ShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.kleidia.clawchat
        PRODUCT_NAME: ClawChat
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "3"
        DEVELOPMENT_TEAM: D7HDY2ST3C
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_GENERATION_MODE: GeneratedByXcode
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    # Uncomment when App Group is configured in Apple Developer Portal:
    # entitlements:
    #   path: ClawChat.entitlements
    #   properties:
    #     com.apple.security.application-groups:
    #       - group.io.kleidia.clawchat
    info:
      path: ClawChat-Info.plist
      properties:
        CFBundleDisplayName: ClawChat
        CFBundleName: ClawChat
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: ClawChat uses the microphone for voice input to send messages
        NSSpeechRecognitionUsageDescription: ClawChat uses speech recognition to transcribe your voice messages
        NSCameraUsageDescription: ClawChat uses the camera to capture photos for AI analysis
        NSPhotoLibraryUsageDescription: ClawChat accesses your photo library to share images with the AI
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true

  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.kleidia.clawchat.share
        PRODUCT_NAME: ShareExtension
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "3"
        DEVELOPMENT_TEAM: D7HDY2ST3C
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        SKIP_INSTALL: YES
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.io.kleidia.clawchat
    info:
      path: ShareExtension/Info.plist
